build:
    nodes:
        tests:
            project_setup:
                override:
                    - 'true'
            environment:
                php:
                    version: 7.2
            tests:
                override:
                    -
                        command: 'vendor/bin/simple-phpunit --coverage-clover=some-file'
                        coverage:
                            file: 'some-file'
                            format: 'clover'
                    - php-scrutinizer-run
filter:
    excluded_paths:
        - tests/
    dependency_paths:
        - vendor/

checks:
    php:
        excluded_dependencies:
            - phpstan/phpstan
