language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1

env:
  matrix:
    - DEPENDENCIES='low'
    - DEPENDENCIES='stable'
    - DEPENDENCIES='dev'

matrix:
  allow_failures:
    - env: DEPENDENCIES='dev'
  fast_finish: true

before_install:
  - composer selfupdate
  - if [ "$DEPENDENCIES" == "low" ]; then composer config disable-tls true; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer config secure-http false; fi;

install:
  - phpenv rehash
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - './vendor/bin/simple-phpunit --testdox'

notifications:
  email: false
