language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2

env:
  matrix:
    - DEPENDENCIES='low'
    - DEPENDENCIES='stable'
    - DEPENDENCIES='dev'

matrix:
  allow_failures:
    - env: DEPENDENCIES='dev'
    - php: 7.2
  exclude:
    - php: 7.2
      env: DEPENDENCIES='low'
  fast_finish: true

before_install:
  - composer selfupdate
  - if [ "$DEPENDENCIES" == "low" ]; then composer config disable-tls true; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer config secure-http false; fi;

install:
  - phpenv rehash
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest --prefer-stable; fi;

script:
  - 'if [ "$DEPENDENCIES" == "dev" ] || [ "$DEPENDENCIES" == "low" ]; then
      ./vendor/bin/simple-phpunit;
    else
      ./vendor/bin/simple-phpunit --testdox --coverage-text;
    fi;'
  - './vendor/bin/phpstan analyse -l 4 -c phpstan.neon src;'

notifications:
  email: false
