site_name: 'Symfony Commons Bundle'
site_description: 'Symfony Commons Bundle.'
site_author: 'Dawid Spiechowicz'
repo_url: 'https://github.com/spiechu/symfony-commons-bundle'
repo_name: 'GitHub'
edit_uri: blob/master/
docs_dir: ''
theme: readthedocs
pages:
  - Home: README.md
  - Configuration Reference: src/Resources/doc/configuration_reference.md
  - Features:
      - GET method override: src/Resources/doc/get_method_override.md
      - Response schema validation: src/Resources/doc/response_schema_validation.md
